// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using efscaffold;

#nullable disable

namespace efscaffold.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AdminBoard", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("BoardId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("boardid");

                    b.PrimitiveCollection<int[]>("WinningNumbers")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("winningnumbers");

                    b.HasKey("Id")
                        .HasName("adminboard_pkey");

                    b.ToTable("adminboard", "deadpigeons");
                });

            modelBuilder.Entity("AdminBoardHistory", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("BoardId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("boardid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<int>("TotalWinners")
                        .HasColumnType("integer")
                        .HasColumnName("totalwinners");

                    b.PrimitiveCollection<string[]>("WinningUsers")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("winningusers");

                    b.HasKey("Id")
                        .HasName("adminboardhistory_pkey");

                    b.ToTable("adminboardhistory", "deadpigeons");
                });

            modelBuilder.Entity("Board", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("boolean")
                        .HasColumnName("isopen");

                    b.Property<int>("WeekNumber")
                        .HasColumnType("integer")
                        .HasColumnName("weeknumber");

                    b.HasKey("Id")
                        .HasName("boards_pkey");

                    b.ToTable("boards", "deadpigeons");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("Balance")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Isactive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("users_pkey");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("UserBoard", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("BoardId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("boardid");

                    b.PrimitiveCollection<int[]>("GuessingNumbers")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("guessingnumbers");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("userid");

                    b.Property<int>("WeekRepeat")
                        .HasColumnType("integer")
                        .HasColumnName("weekrepeat");

                    b.HasKey("Id")
                        .HasName("userboard_pkey");

                    b.ToTable("userboard", "deadpigeons");
                });

            modelBuilder.Entity("efscaffold.Models.Admin", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.HasKey("Id")
                        .HasName("admins_pkey");

                    b.ToTable("admins", "deadpigeons");
                });

            modelBuilder.Entity("efscaffold.Models.Transaction", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<int>("Balance")
                        .HasColumnType("integer")
                        .HasColumnName("balance");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("transactiondate");

                    b.Property<string>("Transactionid")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("transactionid");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("userid");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("transactions_pkey");

                    b.ToTable("transactions", "deadpigeons");
                });

            modelBuilder.Entity("efscaffold.Models.UserBoardHistory", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("BoardId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("boardid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<bool>("IsWinner")
                        .HasColumnType("boolean")
                        .HasColumnName("iswinner");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("userid");

                    b.HasKey("Id")
                        .HasName("userboardhistory_pkey");

                    b.ToTable("userboardhistory", "deadpigeons");
                });
#pragma warning restore 612, 618
        }
    }
}
